#!/bin/bash

# Start applets

# Bind media keys
if hash xbindkeys 2>/dev/null; then
  xbindkeys &
fi

# start xscreensaver
if hash xscreensaver 2>/dev/null; then
  xscreensaver -no-splash &

  # Auto-lock after 10 minutes
  if hash xautolock 2>/dev/null; then
    xautolock -time 10 -locker "xscreensaver-command -lock" &
  fi
fi

# Execute power manager
if hash xfce4-power-manager 2>/dev/null; then
  xfce4-power-manager &
fi

if hash nm-applet 2>/dev/null; then
  nm-applet &
fi

if hash redshift-gtk 2>/dev/null; then
  redshift-gtk &
fi

if [ -f $HOME/.update_wallpaper.sh ]; then
  $HOME/.update_wallpaper.sh &
fi
