#!/bin/bash

# start xscreensaver
if hash xscreensaver 2>/dev/null; then
  xscreensaver -no-splash &

  # Auto-lock after 10 minutes
  if hash xautolock 2>/dev/null; then
    xautolock -time 10 -locker "xscreensaver-command -lock" &
  fi
fi

# Start applets
if hash nm-applet 2>/dev/null; then
  nm-applet &
fi

if hash redshift-gtk 2>/dev/null; then
  redshift-gtk &
fi

if [ -f $HOME/.update_wallpaper.sh ]; then
  $HOME/.update_wallpaper.sh &
fi
