#!/bin/bash

# Start applets

# Volumecontrol
if hash volumeicon 2>/dev/null; then
  volumeicon &
fi

# Network-manager
if hash nm-applet 2>/dev/null; then
  nm-applet &
fi

# Bind media keys
if hash xbindkeys 2>/dev/null; then
  xbindkeys &
fi

